// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using dutch_retreat.Data;

namespace dutch_retreat.Migrations
{
    [DbContext(typeof(DutchContext))]
    [Migration("20210516103013_artadde2s")]
    partial class artadde2s
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DutchTreat.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DutchTreat.Data.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("DutchTreat.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ArtDating")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Artist")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ArtistBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ArtistDeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArtistNationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2345,
                            ArtDating = "2017",
                            ArtDescription = "intel core i7",
                            ArtId = "SK-A-2344",
                            Artist = "HP",
                            ArtistBirthDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistDeathDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistNationality = "Made in nigeria",
                            Category = "Laptop",
                            Price = 500000m,
                            Size = "512G SSD",
                            Title = "HP Envy x360"
                        },
                        new
                        {
                            Id = 232,
                            ArtDating = "2019",
                            ArtDescription = "intel core i7",
                            ArtId = "SK-A-3066",
                            Artist = "Lenovo",
                            ArtistBirthDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistDeathDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistNationality = "Made in nigeria",
                            Category = "Laptop",
                            Price = 350000m,
                            Size = "512G SSD",
                            Title = "Lenovo Yoga"
                        },
                        new
                        {
                            Id = 678,
                            ArtDating = "2019",
                            ArtDescription = "128 G",
                            ArtId = "SK-A-3137",
                            Artist = "Apple",
                            ArtistBirthDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistDeathDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistNationality = "Made in nigeria",
                            Category = "Phones",
                            Price = 450000m,
                            Size = "215G SSD",
                            Title = "Iphone 11 pro max"
                        },
                        new
                        {
                            Id = 6734,
                            ArtDating = "2021",
                            ArtDescription = "64 inch",
                            ArtId = "SK-A-2351",
                            Artist = "LG",
                            ArtistBirthDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistDeathDate = new DateTime(2021, 5, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            ArtistNationality = "Made in nigeria",
                            Category = "TV",
                            Price = 567833m,
                            Size = "512G SSD",
                            Title = "Oled TV"
                        });
                });

            modelBuilder.Entity("DutchTreat.Data.Entities.OrderItem", b =>
                {
                    b.HasOne("DutchTreat.Data.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("DutchTreat.Data.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");
                });
#pragma warning restore 612, 618
        }
    }
}
